# Numpy

First we need to install numpy. Usually when you install python, numpy is installed as well but in case you don't have numpy:

In [1]:
!pip install numpy

You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Then we have to import numpy and name it np

In [2]:
import numpy as np

## Creation

<ul>
    <li>How to create array?</li>
    <li>How to create array from list?</li>
    
</ul>

In [3]:
my_list = [0,1,2,3,4,5]

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([0, 1, 2, 3, 4, 5])

We can create different arrays using builtin functions 
of numpy

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2) # with step size 2

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(5) # 1D array

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((2,4)) # 2D array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.random.randint(0,10) # random integer from 0 to 9

3

In [25]:
np.random.randint(0,10,(2,2)) #2D array of random integers from 0 to 9

array([[1, 5],
       [1, 2]])

In [26]:
np.linspace(0,10,6) # five equidistant intervals from 0 to 10

array([ 0.,  2.,  4.,  6.,  8., 10.])

## Available Operations

What is seed?

Basically we set seed so that our result which depends on random numbers
could be reproduced. Meaning that if we run our program, each time we get the same result.

In [29]:
np.random.seed(1)
arr = np.random.randint(0,20,6)

In [31]:
arr

array([ 5, 11, 12,  8,  9, 11])

### Now some useful operations

In [32]:
arr.max()
arr.min()
arr.mean()
arr.argmin() # index location of minimum value
arr.argmax() # index location of maximum value
arr.reshape(2,3) # reshape the 1D array to 2D array if possible
                 

array([[ 5, 11, 12],
       [ 8,  9, 11]])

## Indexing

In [35]:
matrix = np.arange(0,25).reshape(5,5)

In [36]:
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**Indices start from 0** Never forget this fact about python

Lets get the element in row 1 and column2  
This means that we have to index the element at row 0 (1-1)
and column 1 (2-1)

In [37]:
matrix[0,1]

1

How to get row 3?  
How to get column 3?

In [38]:
matrix[2,:] # : means all the columns

array([10, 11, 12, 13, 14])

In [39]:
matrix[:,2] # : means all the rows

array([ 2,  7, 12, 17, 22])

How to extract sub matrix?

In [41]:
matrix[0:2,0:2] # This will extract matrix consisting of
                # rows 1 and 2 and columns 1 and 2

array([[0, 1],
       [5, 6]])

## Masking

Masking is basically extracting elements based on a condition

In [45]:
mask =(matrix > 5) # results in a boolean matrix where we get TRUE for 
        # elements greater than 5 and FALSE otherwise
mask

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

Now let's extract the actual elements

In [46]:
matrix[mask]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])